# Generated by Django 5.0.6 on 2024-06-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название канала')),
                ('channel_id', models.CharField(max_length=250, verbose_name='id канала')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('video_id', models.CharField(max_length=250, verbose_name='Сылка на видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('parts', models.CharField(choices=[('kuji', 'Kuji-podcast'), ('perst', 'Perst fomi')], max_length=100, verbose_name='Разделы')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Видео-ролик',
                'verbose_name_plural': 'Видео-ролики',
            },
        ),
    ]
